//=============================================================================
// v2k_timebase.h — Phase 2 time-base proof: ePWM1 → ADC SOC → EOC ISR (CPU1 only)
//
// Division of labor (boundary with SysConfig):
//   SysConfig owns the static hardware — ePWM1 waveform/dead-band/SOC/TZ, ADCA,
//   DACA, pin mux — and the engine checks conflicts and errata (config checklist
//   in docs/phase2-bringup.md §1).
//   This module owns only the runtime — ISR body and registration, duty (a
//   runtime quantity), EPWMCLKDIV (the clock domain belongs to device.c / the C
//   side), TBCLKSYNC release timing, plus the contract self-check that
//   reconciles safety-critical config against register read-back (v2k_tb_check,
//   same pattern as v2k_assert_layout).
//
// Startup-order contract (protection first, see runtime/v2k_main.c):
//   ① TBCLKSYNC off + v2k_fault_arm()  — lock out pre-emptively before Board_init
//   ② Board_init()                     — syscfg config lands
//   ③ v2k_tb_init() / v2k_fault_init() — self-check + ISR registration + state machine in place
//   ④ v2k_tb_start()                   — release TBCLKSYNC, the time base starts
//=============================================================================
#ifndef V2K_TIMEBASE_H
#define V2K_TIMEBASE_H

#include "../../contracts/v2k_common.h"

//-----------------------------------------------------------------------------
// Time-base parameters (V2K_ISR_HZ can be overridden by a build -D: 20 kHz to
// bring up, 100 kHz to stress-test. Changing the frequency requires changing
// syscfg's EPWM1 Period in lockstep — a v2k_tb_check reconciliation failure means
// ESTOP0. The dual source of the period is a known trade-off, not a virtue: the
// flaw is backstopped by reconciliation, the maintenance tax is real, and the
// ledger and direction of convergence are in docs/phase2-bringup.md "Key decisions")
//-----------------------------------------------------------------------------
#ifndef V2K_ISR_HZ
#define V2K_ISR_HZ          20000u
#endif

// EPWMCLK = PLLSYSCLK / 1 = 200 MHz. Must be /1: F28P65x errata — at EPWMCLKDIV=/2
// TZFRC/TZCLR are occasionally lost, and this platform's state machine relies on
// exactly those two registers for lockout (STOP/initial) and release (START), so
// a loss is a safety issue (syscfg validation flags this too).
// Config source = the syscfg clock tree (the Device_init generated by Device
// Support), asserted by v2k_tb_check from read-back; this macro is only the
// C-side mirror value used to derive PRD.
#define V2K_EPWMCLK_HZ      200000000u
#define V2K_TB_PRD          (V2K_EPWMCLK_HZ / (2u * V2K_ISR_HZ))  // up-down count
#define V2K_ISR_BUDGET_CYCLES (V2K_EPWMCLK_HZ / V2K_ISR_HZ)

// The frequency must divide evenly, otherwise PRD truncation makes the actual ISR frequency deviate from nominal
V2K_STATIC_ASSERT((V2K_EPWMCLK_HZ % (2u * V2K_ISR_HZ)) == 0u);

// CPUTIMER1 (wire_cycle_count) runs at SYSCLKOUT; this mirror exists only to pin
// the load profiler's cross-counter assumption. The profiler adds the ISR-entry
// TBCTR latency (ePWM TBCLK ticks) to the ISR duration (CPUTIMER1/SYSCLK ticks),
// which is meaningful only while one TBCLK tick == one CPUTIMER1 tick, i.e.
// EPWMCLK == SYSCLK (EPWMCLKDIV=/1, errata-mandated above) AND the ePWM time-base
// prescalers are /1 (syscfg: hsClockDiv=CLKDIV=1). Change the clock tree and the
// latency must be rescaled before it is added to cycles.
#define V2K_CPUTIMER_HZ     200000000u
V2K_STATIC_ASSERT(V2K_EPWMCLK_HZ == V2K_CPUTIMER_HZ);

//-----------------------------------------------------------------------------
// Observables (CCS Expressions)
//-----------------------------------------------------------------------------
extern volatile v2k_tick_t g_v2k_tick;     // ISR tick, the platform-wide single time
extern volatile uint16_t g_v2k_isr_lat;    // TBCTR at ISR entry (EPWMCLK ticks, 5 ns)
extern volatile uint16_t g_v2k_isr_lat_min;// Historical min of the above (spread = jitter)
extern volatile uint16_t g_v2k_isr_lat_max;// Historical max. Note it includes a constant
                                           // offset from ADC sample+convert, so read the
                                           // min/max spread, not the absolute value;
                                           // absolute latency is measured on a scope via the GPIO method
extern volatile uint32_t g_v2k_isr_ovf_cnt;// ADC INT overflow count (≠0 = ISR overran)
extern volatile uint32_t g_v2k_isr_cycles; // Most recent ISR cycle count measured by CPUTIMER1
extern volatile uint32_t g_v2k_isr_cycles_max;
extern volatile uint32_t g_v2k_control_cycles; // user control() body only (control_start→control_done); excludes acquire/apply
extern volatile uint32_t g_v2k_control_cycles_max; // peak of the above; redefined in Phase 4.6 (was acquire→apply)
extern volatile uint32_t g_v2k_scope_cycles;   // scope epilogue's separate budget
extern volatile uint32_t g_v2k_scope_cycles_max;
extern volatile uint32_t g_v2k_isr_budget_violation_cnt;

void v2k_tb_init(void);    // EPWMCLKDIV=/1 + contract self-check + duty + ISR registration
void v2k_tb_start(void);   // Release TBCLKSYNC (called after all protection and self-checks are in place)

#endif // V2K_TIMEBASE_H
