//=============================================================================
// v2k_scope.h — shared-memory interface: scope Stream/Capture (control-core → host)
//
// Lock-free SPSC: the CPU1 control ISR is the sole producer (sampling happens
// in ISR context, so all channels are naturally same-tick) and CPU2 is the sole
// consumer; CCS Graph views the post-freeze Capture window through a read-only
// view generated by a CPU1 background task.
//
// ---- Two entry points, one hot path ----
// The host faces two explicit entry points:
//   * Stream: a continuous block stream; the host keeps consuming via BLOCK_REQ,
//     and when the ring is full new blocks are dropped and overrun is reported;
//   * Capture: a device-side triggered freeze window; CPU1 overwrites the ring,
//     evaluates the trigger, fills the post segment, then the host drains it
//     slowly after the freeze.
// Both entry points reuse the same channel binding, ring, and block format, so
// there is no longer a fixed 8-channel group exposed and no second scope hot
// path to maintain.
//
// ---- Channel binding (host selects channels at runtime, no re-flash) ----
// Channel membership is pushed by the host at runtime via DAQ_BIND
// (v2k_scope_bind_t); a channel = an (addr, type) pair:
//   * addr source = the descriptor table (platform quantities + user variables
//     baked in from DWARF at Phase 4.5 build time); the firmware neither
//     distinguishes nor needs to "recognize" them;
//   * samples are copied losslessly at native width: I16/U16 take 2 octets,
//     I32/U32/F32 take 4 octets (the bit pattern goes on the wire as-is; the
//     firmware does no quantization/conversion — physical-quantity scaling is
//     purely host-side display metadata);
//   * a binding may be applied only while mode==OFF (stop sampling before
//     changing channels);
//   * Boot leaves the channel list empty; the host binds channels on demand.
//
// ---- block ----
// The unit of the ring buffer is a block, not a sample:
//   [v2k_block_hdr_t][sample area: tick-major interleave, within each tick laid
//    out in binding order, each channel stored contiguously at native width,
//    stride_octets per tick]
// A block is the payload unit of the on-wire BLOCK_DATA (wire-spec §4.6); header
// + samples go on the wire as-is — this is "memory layout == on-wire format"
// realized on the hot path; CPU2 does no re-encoding.
// The header bind_seq tags the binding generation that produced the block: after
// a re-bind the host discards leftover old blocks by it; stride_octets makes the
// block self-describing (it can be delimited without binding knowledge).
//
// ---- Run states ----
// STREAM: continuous stream. When the ring is full the producer drops the new
//   block and increments overrun_cnt (basic rule 1: never block, never wait on
//   the consumer). The host draws a gap from a jump in block_seq.
// CAPTURE_ARMED/CAPTURE_POST/CAPTURE_FROZEN: the Capture entry. CAPTURE_ARMED
//   overwrites the ring (ignoring rd_idx) and evaluates the trigger tick by
//   tick; on a hit it enters CAPTURE_POST to sample the post segment; after
//   CAPTURE_FROZEN, CPU2 drains by directly indexing the frozen_* fields, not
//   via rd_idx. Once drained the host re-ARMs or switches back to STREAM.
//
// ---- SPSC index protocol ----
// wr_idx/rd_idx are free-running uint16, addressed modulo ring_capacity (a power
// of two):
//   empty: wr_idx == rd_idx     full: (uint16_t)(wr_idx - rd_idx) == ring_capacity
// wr_idx is written only by CPU1 (write the block data first, then publish
// wr_idx); rd_idx is written only by CPU2, and both live in their own core's
// owned RAM region (see v2k_memmap.h) — single writer means lock-free.
//=============================================================================
#ifndef V2K_SCOPE_H
#define V2K_SCOPE_H

#include "v2k_common.h"

//-----------------------------------------------------------------------------
// Capacity constants
//-----------------------------------------------------------------------------
#define V2K_SCOPE_MAX_CH       16u   // Max channels per Stream/Capture
#define V2K_BLOCK_HDR_OCTETS   16u   // On-wire size of the block header
#define V2K_BLOCK_DATA_PREFIX_OCTETS 12u

// Baseline block n_ticks (SCI dumb-pump: 10 tick × 8ch × f32 = 320-octet sample area)
#define V2K_BLOCK_NTICKS_SCI  10u

// Per-type sample width (octets): I16/U16=2, I32/U32/F32=4 (lossless native-width copy)
#define V2K_TYPE_SAMPLE_OCTETS(t) (((t) == V2K_TYPE_I16 || (t) == V2K_TYPE_U16) ? 2u : 4u)

//-----------------------------------------------------------------------------
// Scope states (prod.mode field; the state machine is driven by the CPU1 ISR epilogue)
//-----------------------------------------------------------------------------
#define V2K_SCOPE_OFF     0u
#define V2K_SCOPE_STREAM  1u   // Stream entry: continuous stream, no trigger freeze
#define V2K_SCOPE_CAPTURE_ARMED  2u   // Capture: overwrite the ring + per-tick trigger evaluation
#define V2K_SCOPE_CAPTURE_POST   3u   // Capture: triggered, sampling the post-trigger segment
#define V2K_SCOPE_CAPTURE_FROZEN 4u   // Capture: frozen, awaiting CPU2 drain + host restart

// Trigger edge (cfg.trig_edge; 2/3 reserved for >threshold / <threshold)
#define V2K_TRIG_RISE 0u
#define V2K_TRIG_FALL 1u

// Config and bind result codes (prod.cfg_result / prod.bind_result)
#define V2K_SCOPE_RESULT_OK          0u
#define V2K_SCOPE_RESULT_BAD_STATE   1u
#define V2K_SCOPE_RESULT_BAD_PARAM   2u
#define V2K_SCOPE_RESULT_BAD_TYPE    3u
#define V2K_SCOPE_RESULT_BAD_ADDR    4u
#define V2K_SCOPE_RESULT_NO_CAPACITY 5u

//-----------------------------------------------------------------------------
// Block header (isomorphic in RAM and on the wire, 16 octets / 8 words)
//-----------------------------------------------------------------------------
typedef struct {
    v2k_tick_t start_tick;    // ISR tick of this block's first sample (the platform-wide single time)
    uint16_t   block_seq;     // Incrementing sequence number, wraps; the host detects drops/gaps from jumps
    uint16_t   flags;         // Reserved, set to 0
    uint16_t   n_ticks;       // Number of sample ticks N in this block
    uint16_t   n_ch;          // Channel count M (laid out per tick in binding order, at native width)
    uint16_t   bind_seq;      // Binding generation that produced this block; after a re-bind the host discards non-matching old blocks
    uint16_t   stride_octets; // Sample-area octets per tick = Σ channel widths (block self-describing)
} v2k_block_hdr_t;

V2K_ASSERT_SIZE_BITS(v2k_block_hdr_t, 128u);

//-----------------------------------------------------------------------------
// Producer control block (CPU1-owned region, CPU2 read-only)
//
// C28x word offsets: mode@0 flags@1 cap@2 n_ticks@3 n_ch@4 prescaler@5
//   cfg_ack@6 cfg_result@7 ring_base@8 wr_idx@10 overrun@11 trig_tick@12
//   frz_end@14 frz_cnt@15 state_seq@16 bind_ack@17 bind_result@18 slot_words@19
//-----------------------------------------------------------------------------
typedef struct {
    uint16_t mode;            // V2K_SCOPE_* (CPU1 writes; transitions after handling a cfg request)
    uint16_t flags;           // Reserved, set to 0
    uint16_t ring_capacity;   // Ring capacity (in blocks, a power of two)
    uint16_t block_n_ticks;   // Currently effective N
    uint16_t n_ch;            // Currently effective M (= channel count of the applied binding)
    uint16_t prescaler;       // Currently effective scope sampling decimation
    uint16_t cfg_ack_seq;     // Processed cfg_seq (acknowledge side of the sequence handshake)
    uint16_t cfg_result;      // V2K_SCOPE_RESULT_* (for cfg_ack_seq)
    uint32_t ring_base;       // Base address of the ring data area (CPU1 data-space word address)
    uint16_t wr_idx;          // Free-running write index (in blocks); published after the data is ready
    uint16_t overrun_cnt;     // Cumulative STREAM ring-full block drops
    v2k_tick_t trig_tick;     // Trigger-hit tick (valid in CAPTURE_FROZEN)
    uint16_t frozen_end_idx;  // CAPTURE_FROZEN: index just past the last written block (free-running value)
    uint16_t frozen_count;    // CAPTURE_FROZEN: number of valid blocks (≤ ring_capacity)
    uint16_t state_seq;       // Bumped by 1 on each mode transition (CPU2/host detect state changes)
    uint16_t bind_ack_seq;    // Processed bind_seq (acknowledge side of the sequence handshake)
    uint16_t bind_result;     // V2K_SCOPE_RESULT_* (for bind_ack_seq)
    uint16_t block_slot_words;// Words per block slot in the ring = 8 + n_ticks×stride_words
} v2k_scope_prod_t;

V2K_ASSERT_SIZE_BITS(v2k_scope_prod_t, 320u);

//-----------------------------------------------------------------------------
// Consumer control block (CPU2-owned region, CPU1 read-only)
//-----------------------------------------------------------------------------
typedef struct {
    uint16_t rd_idx;          // Free-running read index (used by STREAM; reset before CAPTURE_FROZEN drain)
    uint16_t reserved;
} v2k_scope_cons_t;

V2K_ASSERT_SIZE_BITS(v2k_scope_cons_t, 32u);

//-----------------------------------------------------------------------------
// Scope config request (CPU2-owned region = host writes via DAQ_CTRL, CPU1 applies)
//
// Sequence handshake: CPU2 fills the remaining fields → writes cfg_seq = old+1
// last (publish). A CPU1 background task copies it stably, validates, and
// prepares the runtime state; once every field is done it publishes the active
// flag to the ISR last.
//-----------------------------------------------------------------------------
typedef struct {
    uint16_t mode_req;        // Target mode: OFF / STREAM / CAPTURE_ARMED
    uint16_t trig_ch_slot;    // Trigger source = a currently-bound channel slot, 0..n_ch-1
    float    trig_level;      // Trigger threshold, in source units; the firmware has no physical-scaling knowledge
    float    trig_hysteresis; // Trigger hysteresis half-width, absolute in source units; 0 = bare threshold
    uint16_t trig_edge;       // V2K_TRIG_*
    uint16_t pre_trig_pct;    // Pre-trigger as a percentage of ring depth, 0..100
    uint16_t prescaler;       // Scope rate override (0 = keep the current value)
    uint16_t record_points;   // Capture target sample-point count; ignored for STREAM/OFF
    uint16_t reserved;        // Set to 0
    uint16_t cfg_seq;         // CPU2 writes this last (publish); the ack is in prod.cfg_ack_seq
} v2k_scope_cfg_t;

V2K_ASSERT_SIZE_BITS(v2k_scope_cfg_t, 192u);

//-----------------------------------------------------------------------------
// Channel bind request (CPU2-owned region = host writes via DAQ_BIND, CPU1 applies)
//
// Constraint: CPU1 applies it only while mode==OFF, otherwise bind_result=BAD_STATE.
//-----------------------------------------------------------------------------
typedef struct {
    uint32_t addr;            // CPU1 data-space word address from the enumerated descriptor table
    uint16_t type;            // V2K_TYPE_* (determines sample width, see V2K_TYPE_SAMPLE_OCTETS)
    uint16_t reserved;        // Set to 0
} v2k_scope_ch_bind_t;

V2K_ASSERT_SIZE_BITS(v2k_scope_ch_bind_t, 64u);

typedef struct {
    uint16_t n_ch;            // 1..V2K_SCOPE_MAX_CH
    uint16_t bind_seq;        // CPU2 writes this last (publish); the ack is in prod.bind_ack_seq
    v2k_scope_ch_bind_t ch[V2K_SCOPE_MAX_CH];
} v2k_scope_bind_t;

V2K_ASSERT_SIZE_BITS(v2k_scope_bind_t, 32u + 64u * V2K_SCOPE_MAX_CH);

//-----------------------------------------------------------------------------
// Derived-size helpers (the ring data area is tiled by block slots; stride = Σ channel widths)
//-----------------------------------------------------------------------------
// Words occupied by one block (C28x: 8-word header + sample area; stride_words = stride_octets/2)
#define V2K_BLOCK_WORDS(n_ticks, stride_words) \
    (8u + (uint32_t)(n_ticks) * (stride_words))
// On-wire octets of one block
#define V2K_BLOCK_OCTETS(n_ticks, stride_octets) \
    (V2K_BLOCK_HDR_OCTETS + (uint32_t)(n_ticks) * (stride_octets))

#endif // V2K_SCOPE_H
