//#############################################################################
// cpu2.c - CPU2 comms core (Phase 3.5 SCI data pump)
//
// Current responsibilities:
//   1. Rendezvous with CPU1 through IPC_sync, wait for descriptor magic, then
//      verify the contract version handshake (v2k_command.h).
//   2. Own the CPU2 plane and CPU2->CPU1 MSGRAM; service the parameter, scope,
//      and command planes.
//   3. Let the SCIA ISR collect octets; run COBS/CRC/message services and TX in
//      the super-loop.
//   4. Acknowledge IPC ping-pong and blink the local status LED. Pad config and
//      CSEL ownership are assigned by CPU1; CPU2 only writes the data register.
//
// CPU2 does not own control time. Block timestamps, sampling epochs, and
// control scheduling all come from CPU1. The local low-rate heartbeat proves
// only that the comms core is still running; it must not enter sampling or
// control timing.
//#############################################################################

#include <string.h>
#include "driverlib.h"
#include "../common/v2k_planes.h"
#include "v2k_cpu2_board.h"
#include "v2k_sci_service.h"

//-----------------------------------------------------------------------------
// Shared-memory entities. Section -> physical-region mapping is in the CPU2
// 28p65x_generic_* linker command files.
//-----------------------------------------------------------------------------
#pragma DATA_SECTION(g_v2k_cpu2_plane, V2K_SECT_CPU2_PLANE)
v2k_cpu2_plane_t g_v2k_cpu2_plane;

#pragma DATA_SECTION(g_v2k_msg_2to1, V2K_SECT_MSG_2TO1)
v2k_msg_2to1_t g_v2k_msg_2to1;

//-----------------------------------------------------------------------------
// Observables for CCS Expressions.
//-----------------------------------------------------------------------------
uint32_t g_pong_cnt;          // Completed ping acknowledgements.
uint16_t g_handshake_state;   // 0=sync, 1=descriptor, 2=bad contract, 3=running.

// NMI backstop, symmetric with CPU1: count, leave a trace, clear flags.
volatile uint32_t g_nmi_cnt;
volatile uint32_t g_nmi_flags_last;
volatile uint32_t g_nmi_shadow_last;

static __interrupt void v2k_nmi_isr(void)
{
    g_nmi_flags_last  = SysCtl_getNMIFlagStatus();
    g_nmi_shadow_last = SysCtl_getNMIShadowFlagStatus();
    g_nmi_cnt++;
    SysCtl_clearAllNMIFlags();
}

void main(void)
{
    uint16_t led_count = 0u;

    v2k_cpu2_board_init_device();
    v2k_cpu2_board_assert_layout(&g_v2k_cpu2_plane, &g_v2k_msg_2to1);

    memset(&g_v2k_cpu2_plane, 0, sizeof(g_v2k_cpu2_plane));
    memset(&g_v2k_msg_2to1, 0, sizeof(g_v2k_msg_2to1));

    //
    // Phase 3.5 SCIA static config (pins/baud/FIFO/module) is generated by
    // SysConfig:
    //   - CPU1 syscfg cpuSel_SCIA->CPU2 makes CPU1 board.c SYSCTL_init call
    //     SysCtl_selectCPUForPeripheralInstance(SYSCTL_CPUSEL_SCIA, CPU2).
    //   - CPU2 syscfg owns the SCI instance (SCIA + GPIO42/43 + 115200 8N1 +
    //     FIFO). The dual SysConfig context generates SCIA pinmux/pad/qual into
    //     CPU1 board.c and SCIA_BASE_init into CPU2 board.c.
    // CPU2 Board_init() would call SYSCTL_init() before SCI_init(); this code
    // deliberately bypasses that aggregate entry, so the board seam keeps the
    // minimum local clock gate needed before SCIA_BASE_init writes SCICCR/BAUD.
    // Do not call full SYSCTL_init() here: it pulls in boot-master-only access
    // control/CPUSEL setup that is invalid on CPU2 and bloats the CPU2 RAM budget.
    //
    v2k_cpu2_board_init_sci_pipe();

    //
    // NMI backstop, symmetric with CPU1.
    //
    Interrupt_initModule();
    Interrupt_initVectorTable();
    SysCtl_clearAllNMIFlags();
    Interrupt_register(INT_NMI, &v2k_nmi_isr);
    SysCtl_enableNMIGlobalInterrupt();
    Interrupt_enable(INT_NMI);
    EINT;
    ERTM;

    //
    // Rendezvous with CPU1.
    //
    IPC_clearFlagLtoR(IPC_CPU2_L_CPU1_R, IPC_FLAG_ALL);
    IPC_sync(IPC_CPU2_L_CPU1_R, IPC_FLAG31);

    //
    // Wait for descriptor publication. Single-writer publish protocol: the
    // table is readable only after magic appears.
    //
    g_handshake_state = 1u;
    while (V2K_CPU1_PLANE_RO->desc_table.hdr.magic != V2K_DESC_MAGIC) { }

    //
    // Contract version handshake. A mismatch means CPU1/CPU2 were flashed from
    // different firmware generations; shared layout is unsafe, so stop in a
    // diagnosable failure state.
    //
    if ((V2K_MSG_1TO2_RO->cpu1_status.contract_ver != V2K_CONTRACT_VER) ||
        (V2K_CPU1_PLANE_RO->desc_table.hdr.contract_ver   != V2K_CONTRACT_VER))
    {
        g_handshake_state = 2u;
        v2k_cpu2_board_panic_halt();
    }
    g_handshake_state = 3u;
    v2k_sci_init();

    for (;;)
    {
        // Ping-pong acknowledgement: acknowledge each observed ping.
        if (IPC_isFlagBusyRtoL(IPC_CPU2_L_CPU1_R, IPC_FLAG0))
        {
            g_pong_cnt++;
            IPC_ackFlagRtoL(IPC_CPU2_L_CPU1_R, IPC_FLAG0);
        }

        // The SCI ISR only collects octets. Protocol parsing, shared-plane
        // services, and TX all run in the super-loop.
        v2k_sci_service();

        // Local diagnostic heartbeat does not enter control time or scope
        // timestamps.
        v2k_cpu2_board_delay_100us();
        led_count++;
        if ((led_count % 10u) == 0u)
        {
            g_v2k_msg_2to1.cpu2_status.heartbeat++;
        }

        // Toggle every 2500 x 100 us, roughly 2 Hz, for visual diagnostics only.
        if (led_count >= 2500u)
        {
            led_count = 0u;
            v2k_cpu2_board_toggle_status_led();
        }
    }
}
