#!/usr/bin/env python3
"""Generate cpu1/v2k_build_hash.h from the current git HEAD."""

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "cpu1" / "v2k_build_hash.h"


def main() -> None:
    short_hash = subprocess.check_output(
        ["git", "rev-parse", "--short=8", "HEAD"], cwd=ROOT, text=True
    ).strip()
    value = int(short_hash, 16)
    content = (
        "// Generated by tools/gen_build_hash.py; do not edit.\n"
        "#ifndef V2K_BUILD_HASH_H\n"
        "#define V2K_BUILD_HASH_H\n\n"
        f"#define V2K_BUILD_HASH 0x{value:08X}uL\n\n"
        "#endif // V2K_BUILD_HASH_H\n"
    )
    OUT.write_text(content, encoding="ascii")
    print(f"{OUT}: {short_hash}")


if __name__ == "__main__":
    main()
