#!/usr/bin/env python3
"""Generate cpu1/tools/v2k_build_hash.h from the current git HEAD."""

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "cpu1" / "tools" / "v2k_build_hash.h"


def main() -> None:
    # The build hash only matters once the host enumerates the descriptor table
    # over the link (from Phase 3.5 on): on reconnect the host sees the header
    # hash has changed and forces a re-enumeration, preventing an old table from
    # being used to read new firmware. In Phase 3 the only consumer is CCS
    # reading memory directly over JTAG, which knows exactly which .out it
    # loaded and has no use for this value. This file is no longer version-
    # controlled (see .gitignore) and is regenerated locally on every build.
    # When git is unavailable, fall back to the sentinel 0 so a missing git
    # does not block the build.
    try:
        short_hash = subprocess.check_output(
            ["git", "rev-parse", "--short=8", "HEAD"],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        value = int(short_hash, 16)
    except (subprocess.CalledProcessError, FileNotFoundError, ValueError):
        short_hash = "no-git"
        value = 0
    content = (
        "// Generated by tools/gen_build_hash.py; do not edit. Not tracked in git.\n"
        "#ifndef V2K_BUILD_HASH_H\n"
        "#define V2K_BUILD_HASH_H\n\n"
        f"#define V2K_BUILD_HASH 0x{value:08X}uL\n\n"
        "#endif // V2K_BUILD_HASH_H\n"
    )
    OUT.write_text(content, encoding="ascii")
    print(f"{OUT}: {short_hash}")


if __name__ == "__main__":
    main()
