#!/usr/bin/env python3
"""Generate cpu1/v2k_build_hash.h from the current git HEAD."""

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "cpu1" / "v2k_build_hash.h"


def main() -> None:
    # build hash 仅在上位机经链路枚举描述符表时才有意义（Phase 3.5 起）：
    # host 重连发现表头 hash 变了即强制重新枚举，杜绝拿旧表读新固件。
    # Phase 3 阶段唯一消费者是 CCS 走 JTAG 直读内存，它清楚自己加载的 .out，
    # 用不到这个值。此文件已不入版本库（见 .gitignore），每次构建本地重生成。
    # git 不可用时退回哨兵 0，不让缺失 git 卡住构建。
    try:
        short_hash = subprocess.check_output(
            ["git", "rev-parse", "--short=8", "HEAD"],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        value = int(short_hash, 16)
    except (subprocess.CalledProcessError, FileNotFoundError, ValueError):
        short_hash = "no-git"
        value = 0
    content = (
        "// Generated by tools/gen_build_hash.py; do not edit. Not tracked in git.\n"
        "#ifndef V2K_BUILD_HASH_H\n"
        "#define V2K_BUILD_HASH_H\n\n"
        f"#define V2K_BUILD_HASH 0x{value:08X}uL\n\n"
        "#endif // V2K_BUILD_HASH_H\n"
    )
    OUT.write_text(content, encoding="ascii")
    print(f"{OUT}: {short_hash}")


if __name__ == "__main__":
    main()
