//=============================================================================
// v2k_board_profile.h - LAUNCHXL-F28P65X + smart gate + AS5600 CPU1 profile
//=============================================================================
#ifndef V2K_BOARD_PROFILE_F28P65X_LAUNCHXL_DRV8323RS_AS5600_H
#define V2K_BOARD_PROFILE_F28P65X_LAUNCHXL_DRV8323RS_AS5600_H

#include "../../include/v2k_board_api.h"

#define V2K_BOARD_PROFILE_API_VERSION V2K_BOARD_API_VERSION
#define V2K_BOARD_PROFILE_ID_TEXT "f28p65x_launchxl_drv8323rs_as5600"
#define V2K_BOARD_PROFILE_CPU_TOPOLOGY V2K_BOARD_CPU_TOPOLOGY_DUAL_C28X
#define V2K_BOARD_PROFILE_MEMMAP_HEADER "../cpu1/board/v2k_board_memmap.h"

#define V2K_BOARD_PROFILE_CONTROL_HZ       20000u
#define V2K_BOARD_PROFILE_EPWMCLK_HZ       200000000u
#define V2K_BOARD_PROFILE_CYCLE_COUNTER_HZ 200000000u

#define V2K_BOARD_PROFILE_POWER_CAPS \
    (V2K_BOARD_POWER_CAP_THREE_PHASE_PWM | \
     V2K_BOARD_POWER_CAP_CURRENT_TRIP | \
     V2K_BOARD_POWER_CAP_EXTERNAL_GATE_FAULT | \
     V2K_BOARD_POWER_CAP_GATE_CONFIG_TRANSACTION)

#define V2K_BOARD_PROFILE_SENSOR_CAPS V2K_BOARD_SENSOR_CAP_AS5600

#ifndef V2K_BOARD_POWERSTAGE_MODE
#define V2K_BOARD_POWERSTAGE_MODE V2K_BOARD_POWERSTAGE_MODE_DRY_RUN
#endif

#ifndef V2K_BOARD_POWERSTAGE_POWERED_CONFIG_APPROVED
#define V2K_BOARD_POWERSTAGE_POWERED_CONFIG_APPROVED 0u
#endif

#endif // V2K_BOARD_PROFILE_F28P65X_LAUNCHXL_DRV8323RS_AS5600_H
